<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?php echo $model->sTitle ?></title>

    <!-- Custom CSS -->
    <link href="/css/main.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- we use angular in sub pages which have their own controller -->
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
    <script>
        // this is where we initialize the app global and populate the well
        var app = angular.module("myApp", []);
        app.controller("wellCtrl", function ($scope, $http) {
            $scope.currentUser = null;
            <?php
                if(isset($model->currentUser)){
                    echo '$scope.currentUser = ' . json_encode($model->currentUser);
                }
            ?>;
        });

    </script>
</head>

<body ng-app="myApp">

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Coop Postings</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-8">

            <?php renderBody(); ?>

        </div>

        <!-- Posting Sidebar Widgets Column -->
        <div class="col-md-4">

            <!-- Posting Search Well -->
            <div class="well">
                <h4>Posting Search</h4>
                <div class="input-group">
                    <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                </div>
                <!-- /.input-group -->
            </div>

            <!-- Participation Well -->
            <div class="well" ng-controller="wellCtrl" ng-cloak>
                <div ng-hide="currentUser != null">
                    <h4>Participate in Coop Postings</h4>
                    <p><a class="btn btn-block btn-social btn-google" href="/login/searcher">
                        <span class="fa fa-google"></span> Job Searcher
                    </a></p>
                    <p><a class="btn btn-block btn-social btn-google" href="/login/poster">
                        <span class="fa fa-google"></span> Job Poster
                    </a></p>
                </div>
                <div ng-hide="currentUser == null">
                    <h4>{{currentUser.name}} ... {{currentUser.type}}</h4>
                    <p ng-hide='currentUser == null || currentUser.type == "poster"'>
                        <a class="btn btn-block btn-social btn-google"  data-toggle="modal" data-target="#editHours">
                        <span class="fa fa-plus"></span> Add Volunteer Hours
                    </a></p>
                    <p ng-hide='currentUser == null || currentUser.type == "poster"'>
                        <a class="btn btn-block btn-social btn-google"  data-toggle="modal" data-target="#editProfile">
                        <span class="fa fa-user"></span> Edit Profile
                    </a></p>
                    <p ng-hide='currentUser == null || currentUser.type == "searcher"'>
                        <a class="btn btn-block btn-social btn-google" data-toggle="modal" data-target="#createUpdate">
                        <span class="fa fa-bullhorn"></span> Create Posting
                    </a></p>
                    <p><a class="btn btn-block btn-social btn-google" href="/logout">
                        <span class="fa fa-sign-out"></span> Logout
                    </a></p>
                </div>
            </div>

            <!-- Posting Categories Well -->
            <div class="well">
                <h4>Posting Categories</h4>
                <div class="row">
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            <li><a href="#">Category Name</a>
                            </li>
                            <li><a href="#">Category Name</a>
                            </li>
                            <li><a href="#">Category Name</a>
                            </li>
                            <li><a href="#">Category Name</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.col-lg-6 -->
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            <li><a href="#">Category Name</a>
                            </li>
                            <li><a href="#">Category Name</a>
                            </li>
                            <li><a href="#">Category Name</a>
                            </li>
                            <li><a href="#">Category Name</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.col-lg-6 -->
                </div>
                <!-- /.row -->
            </div>

        </div>
    </div>
    <!-- /.row -->

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </footer>
</div>
<!-- /.container -->
<!-- Add Posting -->
<div class="modal fade" id="createUpdate" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Create Posting</h4>
            </div>
            <div class="modal-body">
                <p>form fields to add a posting would go here</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal"><i class="fa fa-floppy-o"></i></i>&nbsp;Save</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>

    </div>

</div>

<!-- Edit Profile -->
<div class="modal fade" id="editProfile" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Edit Profile</h4>
            </div>
            <div class="modal-body">
                <p>form fields for profile would go here</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal"><i class="fa fa-floppy-o"></i></i>&nbsp;Save</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>

    </div>

</div>
<!-- Add Posting -->
<div class="modal fade" id="editHours" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Volunteer Hours</h4>
            </div>
            <div class="modal-body">
                <p>a table of the hours with form fields to add more hours would go here</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal"><i class="fa fa-floppy-o"></i></i>&nbsp;Save</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>

    </div>

</div>

<!-- jQuery -->
<script src="/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="/js/bootstrap.min.js"></script>

</body>

</html>
