<?php
if(!isset($model->sTitle)){
    $model = json_decode($model);
    $model->sTitle = $model->data[0]->title;
}
layout("layout.phtml");
$model = $model->data[0];
?>

<!-- Title -->
<h1 itemprop="title"><?php echo $model->title ?></h1>

<!-- Author -->
<p class="lead">
    by <span itemprop="hiringOrganization" itemscope itemtype="http://schema.org/Organization"><span itemprop="name"><?php echo $model->hiringOrganizationName ?></span></span>
</p>

<hr>

<!-- Date/Time -->
<p><span class="glyphicon glyphicon-time"></span> Posted on <span itemprop="datePosted"><?php echo $model->datePosted ?></span></p>

<hr>

<!-- Preview Image In this spot we would put a map-->
            <div style="overflow:hidden;height:350px;width:100%;">
                <script src="https://maps.google.com/maps/api/js"></script>
                <script>
                    var latitude = <?php echo $model->jobLocationLatitude ?>;
                    var longitude = <?php echo $model->jobLocationLongitude ?>;
                    google.maps.event.addDomListener(window, "load", function(){
                        var myOptions = {
                            zoom: 14,
                            center: new google.maps.LatLng(latitude, longitude),
                            mapTypeId: google.maps.MapTypeId.ROADMAP,
                            scrollwheel: false
                        };
                        map = new google.maps.Map(document.getElementById("gmap_canvas"), myOptions);
                        marker = new google.maps.Marker({
                            map: map,
                            position: new google.maps.LatLng(latitude, longitude)
                        });
                        infowindow = new google.maps.InfoWindow({
                            content: "<b><?php echo $model->hiringOrganizationName ?></b><br/><?php echo $model->hiringOrganizationAddress ?>"
                        });
                        google.maps.event.addListener(marker, "click", function () {
                            infowindow.open(map, marker);
                        });
                        infowindow.open(map, marker);
                    });
                </script>
                <div id="gmap_canvas" style="height:350px;width:100%;"></div>
                <style>
                    #gmap_canvas img {
                        max-width: none!important;
                        background: none!important
                    }
                </style>
            </div>

<hr>

<!-- Post Content ... This is where you will put in data from the database-->
<p class="lead">Requirements</p>
<p><?php echo $model->experienceRequirements ?></p>
<p class="lead">Responsibilities</p>
<p><?php echo $model->responsibilities ?></p>

<hr>

<!-- Blog Comments -->

<!-- Comments Form -->
<div class="well">
    <h4>Leave a Comment:</h4>
    <form role="form">
        <div class="form-group">
            <textarea class="form-control" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

<hr>

<!-- Posted Comments -->

<!-- Comment -->
<div class="media">
    <a class="pull-left" href="#">
        <img class="media-object" src="http://placehold.it/64x64" alt="">
    </a>
    <div class="media-body">
        <h4 class="media-heading">Start Bootstrap
            <small>August 25, 2014 at 9:30 PM</small>
        </h4>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
    </div>
</div>

<!-- Comment -->
<div class="media">
    <a class="pull-left" href="#">
        <img class="media-object" src="http://placehold.it/64x64" alt="">
    </a>
    <div class="media-body">
        <h4 class="media-heading">Start Bootstrap
            <small>August 25, 2014 at 9:30 PM</small>
        </h4>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
        <!-- Nested Comment -->
        <div class="media">
            <a class="pull-left" href="#">
                <img class="media-object" src="http://placehold.it/64x64" alt="">
            </a>
            <div class="media-body">
                <h4 class="media-heading">Nested Start Bootstrap
                    <small>August 25, 2014 at 9:30 PM</small>
                </h4>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
        </div>
        <!-- End Nested Comment -->
    </div>
</div>

